### PR TITLE
Add loading indicator for form submission

### PR DESCRIPTION
**Pull request by eric-ricky**
I have made the following changes:

- [x] Updated the form submission logic to trigger the loading indicator.
- [x] Added a loading indicator component to display `Generating...` during form submission.
- [x] Styled the loading indicator component.

### CODE REVIEW

**Review by Ranamalsingh12 — CHANGES_REQUESTED** [review]
Hey @eric-ricky,
I saw your code and also run it on my system. So after reviewing it I saw some fields where it needs improvement. 
-> When you start the loading instead of showing ("Generating.... on the submit input and on the output side) you can show a loading bar which will lead to better the user experience instead of just showing Generating....


Thanks and hope that you will consider these changes in your code and also, I like you to remove these extra spaces from you code and then push it.

**Comment by eric-ricky** [comment]
Thanks for your feedback, @Ranamalsingh12
 
I'll update the code accordingly and let you know once it's ready for another review.

**Comment by Ranamalsingh12** [comment]
Sure Eric,
If you need any help regarding anything please feel free to ask me.

**Review by Ranamalsingh12 — CHANGES_REQUESTED** [review]
Changes looks good Eric but please squash these three commits into a single commit.

**Review by Ranamalsingh12 — CHANGES_REQUESTED** [review]
Changes looks good Eric but please squash these three commits into a single commit.

**Comment by eric-ricky** [comment]
Done, squashed commits into one. Thanks!

**Comment by logankilpatrick** [comment]
I am taking a pass at this in a new PR, thanks for the flag!

**Pull request closed without merging**
